#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/clone/functions"

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
#    --app-json-url)
#    APP_JSON_URL="$2"
#    shift # past argument
#    shift # past value
#    ;;
    --app-json-path)
    APP_JSON_PATH="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

clone_main_cmd "$@"
